{% set name = "awslambdaric" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/awslambdaric-{{ version }}.tar.gz
    sha256: f42161dd92b559d08f2ebd9e442a905d9bfa7c6f66896b9fd1395aa6f061f6a6
  # Please see awslabs/aws-lambda-cpp#94, remove once aws-lambda-cpp is upgraded to 0.2.7
    patches:
      - aws-lambda-cpp-0.2.6-update-backward-cpp.patch
  - url: https://raw.githubusercontent.com/bombela/backward-cpp/v1.6/backward.hpp
    sha256: 404aa26ecc36be08f92c03b05505561e064f6f1f7cffcbda77a7d4959e4c07f2
    folder: deps/patches
    fn: backward.h

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}  # [linux]
    - {{ stdlib("c") }}    # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - automake  # [linux]
    - autoconf  # [linux]
    - cmake  # [linux]
    - libtool  # [linux]
    - make  # [linux]
    - pkg-config  # [linux]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - simplejson >=3.18.4

test:
  imports:
    - awslambdaric
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-lambda-python-runtime-interface-client
  summary: AWS Lambda Runtime Interface Client for Python
  license: BSD-3-Clause AND Apache-2.0
  license_file:
    - LICENSE
    - THIRD-PARTY-LICENSES

extra:
  recipe-maintainers:
    - raybellwaves
    - sodre
    - '0xbe7a'
